### ISSUE TITLE
wlroots 0.16.x support?

### ISSUE THREAD

**Issue by bda65hp** [werererer/japokwm#54]
Hi, archlinux updated to wlroots 0.16.x. Do you plan to update japokwm?

**Comment by werererer** [comment]
Yeah you are right. I will fix this in the upcoming week. In the time being you can downgrade wlroots.

Note that I am currently just maintaining this project, so I will gurantee that it runs fine.

I won't add any features in the forseeable future. Since I can already do whatever I want.

People are encouraged to use this window manager as a basis to create something amazing.

Thanks for your issue.

**Comment by werererer** [comment]
ok fixed it now will update the archlinux package in a few. days
